### ISSUE TITLE
Acceleration done more simply.

### ISSUE THREAD

**Issue by rin67630** [igorantolic/ai-esp32-rotary-encoder#25]
To do an acceleration ways easier with far less code: 
Just multiply the encoderChanged result by itself (as an absolute value).
encoderChanged * abs(encoderChanged).

example
````
21:10:29.398 -> Value: 16
21:10:30.382 -> Value: 9
21:10:31.371 -> Value: 484
21:10:33.389 -> Value: 100
21:10:34.376 -> Value: 729
21:10:35.360 -> Value: 1
21:10:36.393 -> Value: 529
21:10:37.380 -> Value: 7744
21:10:45.390 -> Value: -1
21:10:47.369 -> Value: -1
21:10:48.359 -> Value: -4
21:10:49.395 -> Value: -4
21:10:51.375 -> Value: -484
21:10:53.397 -> Value: -121
21:10:54.384 -> Value: -2209
````

**Comment by igorantolic** [comment]
It is all about usability in practice not about super-optimizing the code. 
Since suggested change is not described that may improve user experience I will close this open issue. 
I hope rin will agree.

However, I am always happy that people show me the better way for solving things.
But in this particular case, we should consider if the proposed will not lower CX. This I tested for a longer time using different solutions, but in the end, I found the one I like - it is really accelerating well but on the other hand satisfy fine-tuning.

Shown values in an example where after lowering 16->9 a value jumps directly to 484 then 100 then  719 .. 1.... I am not so convinced yet.
Until someone will implement selection of acceleration method and let users tune it  I will close issue
