### ISSUE TITLE
Disable Acceleration | Number Selector

### ISSUE THREAD

**Issue by ErikOostveen** [igorantolic/ai-esp32-rotary-encoder#36]
Hi - this is a great library. Thank you for your time developing this.

I am using the example in: [https://github.com/igorantolic/ai-esp32-rotary-encoder/blob/master/examples/Number-select/Number-select.ino](url) to build a MIDI Master clock. 

The acceleration feature, which is great for many uses, doesn't, however, work very well in changing the tempo - it can make changing tempo go very abrupt at times.

Q: how can I disable the acceleration feature in the sample code? 

Cheers, Erik

**Comment by igorantolic** [comment]
Set acceleration to 1?

sri, 16. ožu 2022. u 14:35 Erik Oostveen ***@***.***> napisao
je:

**Comment by ErikOostveen** [comment]
Tried that with `rotaryEncoder.setAcceleration(0); ` but that doesn't compile.

... I decided to just tweak AiEsp32RotaryEncoderNumberSelector.h by adding `encoder->setAcceleration(0);` underneath the acceleration if/else conditions.

**Comment by iotregenesis** [comment]
hi,
Excuse me for jumping in, instead of creating new issue, but this is very relevant to my problem.

I too could not disable the acceleration, be it with:
Encoder->disableAcceleration(), nor
Encoder->setAcceleration(0), nor
Encoder->setAcceleration(1)

The acceleration was still there.

Since I only needed delta value of encoder movement, so my workaround was like this:
```
    Encoder->begin();
    Encoder->setup(dialEncoderISR);
    Encoder->setBoundaries(-2, 2, false);
    Encoder->setAcceleration(1);
```

By doing this, even though the acceleration was still working, the value was maximum limited to -2 for CCW or 2 for CW.

But, I think it will be nice thou if this awesome library can have the acceleration control working.
I am using ESP32 with PlatformIO and the library version `igorantolic/Ai Esp32 Rotary Encoder@^1.4`

Cheers,

**Comment by igorantolic** [comment]
should be fine now. If not we wil reopen
