### ISSUE TITLE
question: button long press vs short press

### ISSUE THREAD

**Issue by relax81** [igorantolic/ai-esp32-rotary-encoder#42]
Thank you for this great library which works very well. 
I'm trying to implement it into a project where I have to differentiate between a long and short button press. 
I've tried it with something like this because I thought maybe I could use the maximumWaitMilliseconds for my case

```
if (rotaryEncoder.isEncoderButtonClicked(400))
      {
        shortPress();
      }
 else if (rotaryEncoder.isEncoderButtonClicked(2000))
      {
        longPress();
      }
```
      
which kind of works but causes an exception and crashes the ESP if I hold the button for much longer (like 10 seconds). 
I would appreciate any tips on how to implement it in a correct way. I couldn't find anything for it in the examples. 

I'm a novice at programming so maybe I miss something obvious(?).

**Comment by john-** [comment]
Any luck with reliably detecting long vs. short button presses?  It looks like in my version 1.2 use of library I "rolled my own" button press detection to distinguish long vs. short press.  As I move to version 1.4 I am looking to something more robust.

**Comment by igorantolic** [comment]
There is no need that this library solves such special cases.
Just read a PIN directly to detect if it is up or down.
Then use an existing solution that is general for any button, or write your own.
As @relax81 found out you need smart implementation which will not make the microcontroller control mechanism that the code is blocked. 
On button down detected (was up and now is down) remember the time when that happened. But don't wait here for the button up but rather let other code runs and on the next cycle come again and simply check if it was DOWN and now is UP (or is still down so again go and do normal business).
Finally, on the DOWN to UP change calculate the time difference.
Based on that you can have very short, short, long, or very long press (as many different events as you want).

But again this is primarily a rotary encoder library than an innovative button library. Combine to have what you need for your use case.

I cannot recommend any button lib, because I write my own code for special use cases that I need to solve (unfortunately without thinking to make a library out of that that would be simple enough for use.

Some people were solving double and triple button click, so I would say it is all out of the scope of this library.

**Comment by john-** [comment]
Thanks @igorantolic.  That makes sense and I will continue to use my own long press detection logic.
